### ISSUE TITLE
Server and collector entry scripts are not executable

### ISSUE THREAD

**Issue by pearj** [Dynatrace/Dynatrace-Docker#10]
I tried to build EAP 7 and I have found that the permissions on 
* Dynatrace-Collector/build/scripts/run-collector-process.sh
* Dynatrace-Server/build/scripts/run-server-process.sh   
Are not executable

**Comment by BlazejT** [comment]
Hi @pearj. We haven't noticed such behaviour. Please check EOLs and if they are LF, because Git on Windows can convert all files to CRLF by default. You should check your settings.

If they are CRLF, try to convert to LF and run docker-compose again:
`find <YOUR_WORKDIR> -type f -print0 | xargs -0 dos2unix`

If it does not help, please provide us some more info (logs).

Thanks,
BT
